server: 
  port: 9000 
  
spring: 
  application: 
    name: 
      zuul-gateway 

eureka: 
  client:
    serviceUrl: 
      defaultZone: http://localhost:5000/eureka/  
      
zuul: 
  routes: 
    employee: # 自定义路由规则的名称。在底层的数据结构中是 Map 的键 
      serviceId: atguigu-feign-consumer #目标微服务名称，ZuulRoute 类型的一个属性
      path: /zuul-emp/** #用来代替目标微服务名称的路径， ZuulRoute 类型的一个属性
      