server:
   port: 1000
   
eureka:
   client:
      serviceUrl: #配置当前微服务作为客户端访问Eureka服务器端时使用的地址
         defaultZone: http://localhost:5000/eureka/
         
spring: 
   application:
      name: atguigu-provider